#!/bin/bash

# VHOST 1.1
# virtual host generator
# Joel Buchs - 2014
#-----------------------

#some usefull variables
dirUsrBin="/usr/lib/cgi-bin"
dirShareDoc="/usr/share/doc/"
vhostpath=''
symfDirName=''
symfRootDir="web"
message=''

#welcome
cat << "EOF"

        _                  _     __      __  
       | |                | |   /  |    /  | 
__   __| |__    ___   ___ | |_  `| |    `| | 
\ \ / /| '_ \  / _ \ / __|| __|  | |     | | 
 \ V / | | | || (_) |\__ \| |_  _| |_ _ _| |_
  \_/  |_| |_| \___/ |___/ \__| \___/(_)\___/

				BY JOEL BUCHS                                         	
   
 
EOF

printf "AVAILABLE COMMANDS\n\n sudo vhost -symfony\n sudo vhost -chmod\n sudo vhost install\n sudo vhost update\n\n"

#install function
function install {
	#delete if already installed
	if [ -f /usr/bin/vhost ]
	then
		sudo rm /usr/bin/vhost
	fi

	#cp script in the right directory
	sudo cp ./vhost /usr/bin/vhost

	#chmod the files
	sudo chmod a+x ./vhost /usr/bin/vhost

	printf "The programm will restart in a few seconds..."

	sleep 3

	sudo vhost
}

#update function
function update {
	#check if git is present
	if git --version 2>&1 >/dev/null
	then
		git pull origin master
		install
	else
		printf "you need to have Git installed to make an update !"
	fi
}

#check for install
if [ "$1" = "install" ] 
then
	install
fi


#check for update
if [ "$1" = "update" ] 
then
	update
fi

#create new directory
echo "Please enter the name of the new website : "
read dirName

echo "root directory creation..."
sudo mkdir "/var/www/$dirName"

#check if project using symfony
if [ "$1" = "-symfony" ] || [ "$2" = "-symfony" ]
then
	symfDirName="$dirName/$symfRootDir"
	sudo mkdir "/var/www/$dirName/web"
	message="<br><br>Please remove the <b>/web</b> directory and install your symfony project in <b>/var/www/$dirName</b>"
else
	symfDirName="$dirName"
fi


sudo touch "/var/www/$symfDirName/index.html"

echo "<h1>It works !!!</h1><p>Site successfully initialized! This file is located in <b>/var/www/$symfDirName</b>. $message</p>" > "/var/www/$symfDirName/index.html"

#create vhost file
vhostpath="/etc/apache2/sites-available/$dirName.conf"
sudo touch $vhostpath

#vhost variables
echo "ServerName (for instance : local.mysite.ch) : "
read serverName

echo "Please enter the website administrator's email address : "
read serverAdmin

echo "creating the virtual host..."

sudo chmod 644 $vhostpath

#virtual host generation
sudo cat <<EOF >> "$vhostpath"
<VirtualHost *:80>
	ServerAdmin $serverAdmin
	ServerName $serverName

	DocumentRoot /var/www/$symfDirName
	<Directory />
		Options FollowSymLinks
		AllowOverride All
	</Directory>
	<Directory /var/www/$symfDirName>
		Options Indexes FollowSymLinks MultiViews
		AllowOverride All
		Order allow,deny
		allow from all
	</Directory>

	ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
	<Directory $dirUsrBin>
		AllowOverride None
		Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
		Order allow,deny
		Allow from all
	</Directory>

	ErrorLog /var/log/apache2/error.log

	LogLevel warn

	CustomLog /var/log/apache2/access.log combined

    Alias /doc/ $dirShareDoc
    <Directory $dirShareDoc>
        Options Indexes MultiViews FollowSymLinks
        AllowOverride None
        Order deny,allow
        Deny from all
        Allow from 127.0.0.0/255.0.0.0 ::1/128
    </Directory>

</VirtualHost>
EOF



echo "website activation..."
sudo a2ensite $dirName.conf

echo "adding an entry to the host file..."
sudo sed -i '1s/^/127.0.0.1 \t'"$serverName"'\n/' /etc/hosts

#chmod (optionnal)
if [ "$1" = "-chmod" ] || [ "$2" = "-chmod" ]
then
	sudo chmod -R 777 "/var/www/$dirName"
fi

echo "restarting Apache..."
sudo /etc/init.d/apache2 reload

echo "Finished! Your website is now available to this address : $serverName"
